ProjectCV.WEBUI/Controllers/UserProfileController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectCV.BLL;
using ProjectCV.DAL.DTOs.UserProfileDto;
using ProjectCV.ENTITY.Entities;

namespace ProjectCV.WEBUI.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly UserProfileService _userProfileService;
        private readonly IMapper _mapper;
        public UserProfileController()
        {
            _userProfileService = new UserProfileService();
            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<UserProfileUpdateDTO, UserProfile>();
                cfg.CreateMap<UserProfile, UserProfileUpdateDTO>();
                
            }).CreateMapper();
        }
        public IActionResult Index()
        {
            //var user = _userProfileService.GetUserProfile();
            //return View(user);
            return View();
        }

        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return BadRequest("Invalid user ID.");
            }
            var UserProfile = _userProfileService.GetUserProfile();
            ViewBag.UserProfileSocial = UserProfile.SocialMedias;
            if (UserProfile == null)
            {
                return NotFound("User not found.");
            }
            var userProfileDto = _mapper.Map<UserProfileUpdateDTO>(UserProfile);
            return View(userProfileDto);
        }

        
        [HttpPost]
        public async Task<ActionResult> Update(UserProfileUpdateDTO model, IFormFile profileFile, IFormFile backgroundFile)
        {
            ModelState.Remove("ProfileImage");
            ModelState.Remove("profileFile");
            ModelState.Remove("BackgroundImage");
            ModelState.Remove("BackgroundFile");

            if (ModelState.IsValid)
            {
                // 📸 Profil resmi güncelleme
                if (profileFile != null && profileFile.Length > 0)
                {
                    string newFileName = profileFile.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img", newFileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await profileFile.CopyToAsync(stream);
                    }

                    model.ProfileImage = newFileName;
                }
                else
                {
                    // Yeni dosya yoksa mevcut resmi koru
                    var existingUser = _userProfileService.GetUserProfile();
                    model.ProfileImage = existingUser.ProfileImage;
                }

                // 🖼️ Arka plan resmi güncelleme
                if (backgroundFile != null && backgroundFile.Length > 0)
                {
                    string newFileName2 = backgroundFile.FileName;
                    var path2 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img", newFileName2);

                    using (var stream = new FileStream(path2, FileMode.Create))
                    {
                        await backgroundFile.CopyToAsync(stream);
                    }

                    model.BackgroundImage = newFileName2;
                }
                else
                {
                    // Yeni dosya yoksa mevcut arka planı koru
                    var existingUser = _userProfileService.GetUserProfile();
                    model.BackgroundImage = existingUser.BackgroundImage;
                }

                var userProfile = _mapper.Map<UserProfile>(model);
                _userProfileService.Update(userProfile);

                return RedirectToAction("Index");
            }

            var userProfileView = _userProfileService.GetUserProfile();
            ViewBag.UserProfileSocial = userProfileView.SocialMedias;
            return View(model);
        }


    }
}

ProjectCV.WEBUI/Views/UserProfile/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
<!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    
    </div>
    <!-- /.content -->

ProjectCV.WEBUI/Views/UserProfile/Update.cshtml
@using ProjectCV.DAL.DTOs.UserProfileDto
@model UserProfileUpdateDTO

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">User Profile</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-action="Update" asp-controller="UserProfile" method="post" enctype="multipart/form-data">
            @* user profile section *@
            <input type="hidden" />
            <div class="card-body">

                <div class="form-group">
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <label> Name</label>
                    <input type="text" name="Name" value="@Model.Name" class="form-control"  placeholder="Type your name">
                </div>
                <div class="form-group">
                    <label>Surname</label>
                    <input type="text" name="Surname" value="@Model.Surname" class="form-control" placeholder="Type your name">
                </div>
                    @for (int i=0; i< Model.SocialMedias.Count; i++)
                    {
                    <div class="form-group">
                        <label><span style="font-weight:bold;color:red">@(i + 1)- Social Media </span></label>
                        <input name="SocialMedias[@i].Name" value="@Model.SocialMedias[i].Name" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label><span style="font-weight:bold;color:mediumslateblue">Social Media URL</span></label>
                        <input name="SocialMedias[@i].Url" type="text" value="@Model.SocialMedias[i].Url" class="form-control">
                    </div>
                    <div class="form-group">
                        <label> <span style="font-weight:bold;color:royalblue">Social Media Icon</span></label>
                        <input name="SocialMedias[@i].Icon" type="text" value="@Model.SocialMedias[i].Icon" class="form-control">
                    </div>
                    }
              
                <div class="form-group">
                    <label for="exampleInputFile">Profile Image</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="profileFile" id="exampleInputFile">
                            <label class="custom-file-label" >Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">Background Image</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="backgroundFile" >
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
            </div>
            

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
<!-- /.content -->