ProjectCV.WEBUI/Controllers/ExperienceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectCV.BLL;
using ProjectCV.DAL.DTOs.ExperienceUpdateDTO;
using ProjectCV.ENTITY.Entities;

namespace ProjectCV.WEBUI.Controllers
{
    public class ExperienceController : Controller
    {
        private readonly ExperienceService _experienceService;
        private readonly IMapper _mapper;
        public ExperienceController()
        {
            _experienceService = new ExperienceService();
            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ExperienceUpdateDTO, Experience>();
                cfg.CreateMap<Experience, ExperienceUpdateDTO>();
            }).CreateMapper();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(ExperienceUpdateDTO modelExp)
        {
            if (ModelState.IsValid)
            {
               
                    var experience = _mapper.Map<Experience>(modelExp);
                    _experienceService.Create(experience);
                
                return RedirectToAction("Update");
            }
            return View(modelExp);
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Update()
        {
            var experiences = _experienceService.GetExperiences();
            var experienceDto = _mapper.Map<List<ExperienceUpdateDTO>>(experiences);
            return View(experienceDto);
        }
        [HttpPost]
        public async Task<ActionResult> Update(List<ExperienceUpdateDTO> experiences)
        {
            if (ModelState.IsValid)
            {
                foreach (var exp in experiences)
                {
                    var experience = _mapper.Map<Experience>(exp);
                    _experienceService.Update(experience);
                }
                return RedirectToAction("Update");
            }
            return View(experiences);
        }

        public IActionResult Delete(int id)
        {
            var result = _experienceService.Find(id);
            if (result != null)
            {
                _experienceService.Delete(result);
                return RedirectToAction("Update");
            }
            return NotFound();

        }
    }
}

ProjectCV.WEBUI/Views/Experience/Create.cshtml
@using ProjectCV.DAL.DTOs.ExperienceDTO;
@model ExperienceCreateDTO;

@{
    ViewData["Title"] = "Certificates";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div> 
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create a new experience or <a href="/Experience/Update" style="color:blue">click to update</a> </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="column">
        </div>
        <form asp-action="Create" asp-controller="Experience" method="post">

            <input type="hidden" />
            <div class="card-body">
                <div class="form-group">


                    <label> Company Name </label>
                    <input asp-for="CompanyName" class="form-control">                    

                    <div class="form-group">
                        <label>Start Date  </label>
                        <input name="StartDate" type="datetime" value="@Model?.StartDate.ToString(" MM-dd-yyyy")" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>End Date  </label>
                        <input name="EndDate" type="datetime" value="@Model?.EndDate.ToString("MM-dd-yyyy")" class="form-control">
                    </div>
                    <label> Title </label>
                    <input asp-for="Title" class="form-control">
                    <label> Text </label>
                    <input asp-for="Text"  class="form-control">

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                </div>
        </form>
        
    </div>
</div>

ProjectCV.WEBUI/Views/Experience/Update.cshtml
@using ProjectCV.DAL.DTOs.ExperienceUpdateDTO
@model List<ExperienceUpdateDTO>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Experience Update</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div>
            <a href="~/Certificate/Create" class="btn btn-success btn-sm"> <i class="fas fa-plus-circle"></i> Create New Certificate </a>
        </div>
        <form asp-action="Update" asp-controller="Experience" method="post">

            <input type="hidden" />
            <div class="card-body">
                <div class="form-group">
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <input type="hidden" name="[@i].Id" value="@Model[i].Id" asp-for="@Model[i].Id" />
                        <label> <span style="font-weight:900; color: orangered"> @(i + 1)- Company Name </span></label>
                        <a href="~/Experience/Delete?id=@Model[i].Id" style="font-size: 0.8rem; " class="btn btn-danger btn-sm px-2 py-0 ms-2"> <i class="fas fa-trash-alt"></i> Delete this Experience </a>

                        <input asp-for="@Model[i].CompanyName" name="[@i].CompanyName" type="text" value="@Model[i].CompanyName" class="form-control">
                        @* <div class="form-group">
                            <label><span style="font-weight:bold;color:dodgerblue">Start Date</span></label>
                            <input asp-for="@Model[i].Institution" name="[@i].Institution" type="text" value="@Model[i].Institution" class="form-control">
                        </div> *@
                        <div class="form-group">
                            <label> <span style="font-weight:bold;color:dodgerblue">Start Date</span></label>
                            <input name="[@i].StartDate" type="datetime" value="@Model[i].StartDate.ToString("dd-MM-yyyy")" class="form-control">
                        </div>
                        <div class="form-group">
                            <label> <span style="font-weight:bold;color:red">End Date</span></label>
                            <input name="[@i].EndDate" type="datetime" value="@Model[i].EndDate.ToString("dd-MM-yyyy")" class="form-control">
                        </div>
                        <div class="form-group">
                            <label> <span style="font-weight:bold;color:greenyellow ">Title </span></label>
                            <input name="[@i].Title" value="@Model[i].Title" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Text </label>
                            <input name="[@i].Text" value="@Model[i].Text" type="text" class="form-control">
                        </div>

                    }


                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
</div>