ProjectCV.WEBUI/Controllers/CertificateController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using ProjectCV.BLL;
using ProjectCV.DAL.DTOs.CertificatesDTO;
using ProjectCV.DAL.DTOs.CertificatesUpdateDTO;
using ProjectCV.DAL.DTOs.EducationDTO;
using ProjectCV.DAL.DTOs.EducationUpdateDTO;
using ProjectCV.ENTITY.Entities;

namespace ProjectCV.WEBUI.Controllers
{
    public class CertificateController : Controller
    {
        private readonly CertificateService _certificateService;
        private readonly IMapper _mapper;
        public CertificateController()
        {
            _certificateService = new CertificateService();
            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<CertificatesUpdateDTO, Certificate>();
                cfg.CreateMap<Certificate, CertificatesUpdateDTO>();
                cfg.CreateMap<Certificate, CertificatesCreateDTO>();
                cfg.CreateMap<CertificatesCreateDTO, Certificate>();
            }).CreateMapper();
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CertificatesCreateDTO certificateDto)
        {
            if (ModelState.IsValid)
            {
                var certificate = _mapper.Map<Certificate>(certificateDto);
                _certificateService.Create(certificate);
                TempData["CreateSuccessMessage"] = "Certificates has been successfully created! check below!";

                return RedirectToAction("Update");
            }
            return View(certificateDto);
        }

        public ActionResult Update()
        {
            var certificate = _certificateService.GetAllCertificates();
            var certificateDto = _mapper.Map<List<CertificatesUpdateDTO>>(certificate);
            return View(certificateDto);
        }
        [HttpPost]
        public async Task<ActionResult> Update(List<CertificatesUpdateDTO> certificates)
        {
            if (ModelState.IsValid)
            {
                foreach (var cert in certificates)
                {
                    var certificate = _mapper.Map<Certificate>(cert);
                    _certificateService.Update(certificate);
                }
                TempData["UpdateSuccessMessage"] = "Certificates has been successfully updated!";
                return RedirectToAction("Update");
            }
            return View(certificates);
        }
        public IActionResult Delete(int id)
        {
            var skillId = _certificateService.Find(id);
            if (skillId != null)
            {
                _certificateService.Delete(skillId);
                TempData["SuccessMessage"] = "Certificate has been successfully deleted";
                return RedirectToAction("Update");
            }
            return NotFound();

        }
    }
}

ProjectCV.WEBUI/Views/Certificate/Create.cshtml
@using ProjectCV.DAL.DTOs.CertificatesDTO
@model CertificatesCreateDTO;

@{
    ViewData["Title"] = "Certificates";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Certificates or <a href="/Certificate/Update" style="color:blue">click to update</a> </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div class="column">
        </div>
        <form asp-action="Create" asp-controller="Certificate" method="post">

            <input type="hidden" />
            <div class="card-body">
                <div class="form-group">


                    <label> Certificate Name </label>
                    <input asp-for="Name" class="form-control">

                    <label> Institution Name </label>
                    <input name="Institution" type="text" value="@Model?.Institution" class="form-control">

                    <div class="form-group">
                        <label>Start Date  </label>
                        <input name="StartDate" type="datetime" value="@Model?.StartDate.ToString(" MM-dd-yyyy")" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>End Date  </label>
                        <input name="EndDate" type="datetime" value="@Model?.EndDate.ToString("MM-dd-yyyy")" class="form-control">
                    </div>                   

                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
</div>

ProjectCV.WEBUI/Views/Certificate/Update.cshtml
@using ProjectCV.DAL.DTOs.CertificatesUpdateDTO
@model List<CertificatesUpdateDTO>;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Certificates Update</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <div>
        <a href="~/Certificate/Create" class="btn btn-success btn-sm"> <i class="fas fa-plus-circle"></i> Create New Certificate </a>
        </div>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
                
            </div>
        }
        @if (TempData["UpdateSuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
            </div>
        }
        @if (TempData["CreateSuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["CreateSuccessMessage"]
            </div>
        }
        <form asp-action="Update" asp-controller="Certificate" method="post">

            <input type="hidden" />
            <div class="card-body">
                <div class="form-group">
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <input type="hidden" name="[@i].Id" value="@Model[i].Id" asp-for="@Model[i].Id" />
                        <label> <span style="font-weight:900; color: orangered"> @(i + 1)- Institution Name </span></label>
                        <a href="~/Certificate/Delete?id=@Model[i].Id" style="font-size: 0.8rem; " class="btn btn-danger btn-sm px-2 py-0 ms-2"> <i class="fas fa-trash-alt"></i> Delete this Certificate </a>

                        <input asp-for="@Model[i].Name" name="[@i].Name" type="text" value="@Model[i].Name" class="form-control">
                        <div class="form-group">
                            <label><span style="font-weight:bold;color:dodgerblue">Institution Name</span></label>
                            <input asp-for="@Model[i].Institution" name="[@i].Institution" type="text" value="@Model[i].Institution" class="form-control">
                        </div>
                        <div class="form-group">
                            <label> <span style="font-weight:bold;color:red">Start Date</span></label>
                            <input asp-for="@Model[i].EndDate" name="[@i].StartDate" type="datetime" value="@Model[i].StartDate.ToString("dd-MM-yyyy")" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Degree </label>
                            <input name="[@i].EndDate" value="@Model[i].EndDate.ToString("dd-MM-yyyy")" type="text" class="form-control">
                        </div>
                        
                    }

                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
</div>