ProjectCV.WEBUI/Controllers/SkillController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectCV.BLL;
using ProjectCV.DAL.DTOs.SkillDTO;
using ProjectCV.DAL.DTOs.SkillUpdateDTO;
using ProjectCV.ENTITY.Entities;

namespace ProjectCV.WEBUI.Controllers
{
    public class SkillController : Controller
    {
        private readonly IMapper _mapper;
        private readonly SkillService _skillService;

        public SkillController()
        {
            _skillService = new SkillService();
            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<SkillUpdateDTO, Skill>();
                cfg.CreateMap<Skill, SkillUpdateDTO>();
                cfg.CreateMap<SkillCreateDTO, Skill>();
                cfg.CreateMap<Skill, SkillCreateDTO>();
            }).CreateMapper();
        }
        public IActionResult Index()
        {
            var skills = _skillService.GetSkills();
            return View(skills);
        }

        public ActionResult Update()
        {
            var skills = _skillService.GetSkills();
            var skillDtos = _mapper.Map<List<SkillUpdateDTO>>(skills);
            return View(skillDtos); 

            //if (id == null)
            //{
            //    return BadRequest("Invalid skill ID.");
            //}
            //var skill = _skillService.GetSkills().ToList();
            //if (skill == null)
            //{
            //    return NotFound("Skill not found.");
            //}
            //var skillDto = _mapper.Map<List<SkillUpdateDTO>>(skill);
            //return View(skillDto);
        }
        [HttpPost]
        public async Task<ActionResult> Update(List<SkillUpdateDTO> models)
        {
            if (ModelState.IsValid)
            {
                foreach (var m in models)
                {
                    var skill = _mapper.Map<Skill>(m);
                    _skillService.Update(skill);

                }
                return RedirectToAction("Update");

            }
            return View(models);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SkillCreateDTO skillCreateDTO)
        {
            if (ModelState.IsValid)
            {
                
                    var newskill = _mapper.Map<Skill>(skillCreateDTO);
                    _skillService.Create(newskill);

                TempData["SuccessMessage"] = "Skill has been successfully updated!";
                return RedirectToAction("Update");

            }
            else
            {
                TempData["ErrorMessage"] = "Skill rating can not be greater than 100.";

            }
            return View(skillCreateDTO);
        }
        public IActionResult Delete(int id)
        {
            var skill = _skillService.Find(id);
            if (skill == null)
            {
                return NotFound();
            }
            _skillService.Delete(skill);
            TempData["SuccessMessage"] = "Skill has been successfully deleted";
            return RedirectToAction("Update");
        }


    }
}

ProjectCV.WEBUI/Views/Skill/Create.cshtml
@using ProjectCV.DAL.DTOs.SkillDTO
@model SkillCreateDTO


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Skills or <a href="/Skill/Update" style="color:blue" >click to update</a> </h3>            
        </div>
        <div class="column">
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    @TempData["ErrorMessage"]
                    <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-action="Create" asp-controller="Skill" method="post">

            @* Skill update *@
            <input type="hidden" />
            <div class="card-body">
                
                    <div class="form-group">
                        <input type="hidden" />
                        <label> <span style="font-weight:bold;color:orangered"> Skill </span>  </label>
                        <input name="Name" type="text" value="@Model?.Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label> <span style="font-weight:bold;color:gold">Rating</span></label>
                    <input name="Rating" type="number" value="@Model?.Rating" class="form-control">
                    </div>
                

            </div>


            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

ProjectCV.WEBUI/Views/Skill/Index.cshtml
@using ProjectCV.DAL.DTOs.UserProfileDto
@model SkillUpdateDTO

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Skills Update</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-action="Index" asp-controller="Skill" method="post">

            @* Skill update *@
            <input type="hidden"
            <div class="card-body">

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" asp-for="Name" class="form-control" id="name">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Rating</label>
                    <input type="number" asp-for="Rating" class="form-control" id="rating">
                </div>                

                
                
            </div>


            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

ProjectCV.WEBUI/Views/Skill/Update.cshtml
@using ProjectCV.DAL.DTOs.SkillUpdateDTO
@model List<SkillUpdateDTO>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">CV Maker Panel</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Skills Update</h3>            

        </div>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
                <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
        @if (TempData["UpdateSuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["UpdateSuccessMessage"]
                <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
        <div class="column">           
            <a href="~/Skill/Create" class="btn btn-success btn-sm"> <i class="fas fa-plus-circle"></i> Create a New Skill </a>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form asp-action="Update" asp-controller="Skill" method="post">

            @* Skill update *@
            <input type="hidden" />
            <div class="card-body">
                @for (int i = 0;  i < Model.Count; i++)
                {                    
                    <div class="form-group">
                        <input type="hidden" name="[@i].Id" value="@Model[i].Id" />

                        <label> <span style="font-weight:bold;color:orangered"> @(i + 1) - Skill </span>  </label>
                        <a href="~/Skill/Delete?id=@Model[i].Id" style="font-size: 0.8rem; " class="btn btn-danger btn-sm px-2 py-0 ms-2"> <i class="fas fa-trash-alt"></i> Delete Skill </a>

                        <input name="[@i].Name" type="text" value="@Model[i].Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label> <span style="font-weight:bold;color:gold">Rating</span></label>
                        <input name="[@i].Rating" type="number" value="@Model[i].Rating" class="form-control">
                    </div>
                }                        
                
            </div>


            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>